module Powerpoint
  XML_EXTENSION_CONTENT_TYPE           = "application/xml"
  RELATIONSHIP_EXTENSION_CONTENT_TYPE  = "application/vnd.openxmlformats-package.relationships+xml"

  CORE_PROPS_CONTENT_TYPE              = "application/vnd.openxmlformats-package.core-properties+xml"
  EXTENDED_PROPS_CONTENT_TYPE          = "application/vnd.openxmlformats-officedocument.extended-properties+xml"
  THEME_CONTENT_TYPE                   = "application/vnd.openxmlformats-officedocument.theme+xml"
  PPTX_PRESENTATION_CONTENT_TYPE       = "application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"
  PPTX_SLIDE_MASTER_CONTENT_TYPE       = "application/vnd.openxmlformats-officedocument.presentationml.slideMaster+xml"
  PPTX_SLIDE_LAYOUT_CONTENT_TYPE       = "application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml"
  PPTX_SLIDE_CONTENT_TYPE              = "application/vnd.openxmlformats-officedocument.presentationml.slide+xml"
  PPTX_NOTES_MASTER_CONTENT_TYPE       = "application/vnd.openxmlformats-officedocument.presentationml.notesMaster+xml"
  PPTX_NOTES_SLIDE_CONTENT_TYPE        = "application/vnd.openxmlformats-officedocument.presentationml.notesSlide+xml"
  PPTX_PRES_PROPS_CONTENT_TYPE         = "application/vnd.openxmlformats-officedocument.presentationml.presProps+xml"
  PPTX_VIEW_PROPS_CONTENT_TYPE         = "application/vnd.openxmlformats-officedocument.presentationml.viewProps+xml"
  PPTX_TABLE_STYLES_CONTENT_TYPE       = "application/vnd.openxmlformats-officedocument.presentationml.tableStyles+xml"

  THUMBNAIL_RELATIONSHIP_TYPE          = "http://schemas.openxmlformats.org/package/2006/relationships/metadata/thumbnail"
  CORE_PROS_RELATIONSHIP_TYPE          = "http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties"
  EXTENDED_PROS_RELATIONSHIP_TYPE      = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties"
  THEME_RELATIONSHIP_TYPE              = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme"
  IMAGE_RELATIONSHIP_TYPE              = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/image"
  PPTX_MAIN_DOCUMENT_RELATIONSHIP_TYPE = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument"
  PPTX_SLIDE_MASTER_RELATIONSHIP_TYPE  = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster"
  PPTX_SLIDE_LAYOUT_RELATIONSHIP_TYPE  = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout"
  PPTX_SLIDE_RELATIONSHIP_TYPE         = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide"
  PPTX_NOTES_MASTER_RELATIONSHIP_TYPE  = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/notesMaster"
  PPTX_NOTES_SLIDE_RELATIONSHIP_TYPE   = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/notesSlide"
  PPTX_PRES_PROPS_RELATIONSHIP_TYPE    = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/presProps"
  PPTX_VIEW_PROPS_RELATIONSHIP_TYPE    = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/viewProps"
  PPTX_TABLE_STYLES_RELATIONSHIP_TYPE  = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/tableStyles"
end
